//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShessBord.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShessBord.Resources.Strings.ru-RU", typeof(Strings_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Меня зовут Гамов Артём, и это мой проект — Go-приложение на Avalonia UI..
        /// </summary>
        internal static string Application1 {
            get {
                return ResourceManager.GetString("Application1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Классическая настольная игра Go (также известная как &quot;Вейци&quot;) с простым и удобным интерфейсом..
        /// </summary>
        internal static string Application2 {
            get {
                return ResourceManager.GetString("Application2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написана на C# с использованием фреймворка Avalonia UI для кроссплатформенной работы (Windows, Linux, macOS)..
        /// </summary>
        internal static string Application3 {
            get {
                return ResourceManager.GetString("Application3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подходит как для новичков, так и для опытных игроков..
        /// </summary>
        internal static string Application4 {
            get {
                return ResourceManager.GetString("Application4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go — одна из древнейших стратегических игр, сочетающая простые правила с глубокой тактикой. Моя цель — сделать её доступной в цифровом формате, сохранив элегантность и атмосферу..
        /// </summary>
        internal static string Application5 {
            get {
                return ResourceManager.GetString("Application5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avalonia UI — для красивых и отзывчивых интерфейсов..
        /// </summary>
        internal static string Application6 {
            get {
                return ResourceManager.GetString("Application6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReactiveUI — для чистого и гибкого кода..
        /// </summary>
        internal static string Application7 {
            get {
                return ResourceManager.GetString("Application7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET — как основа надежности и производительности..
        /// </summary>
        internal static string Application8 {
            get {
                return ResourceManager.GetString("Application8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотите предложить идею или сообщить об ошибке? Пишите:.
        /// </summary>
        internal static string Application9 {
            get {
                return ResourceManager.GetString("Application9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив партий.
        /// </summary>
        internal static string ArchiveOfParties {
            get {
                return ResourceManager.GetString("ArchiveOfParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блиц.
        /// </summary>
        internal static string Blitz {
            get {
                return ResourceManager.GetString("Blitz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер доски.
        /// </summary>
        internal static string BoardSize {
            get {
                return ResourceManager.GetString("BoardSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пуля.
        /// </summary>
        internal static string Bullet {
            get {
                return ResourceManager.GetString("Bullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас уже есть аккаунт?.
        /// </summary>
        internal static string DoYouAlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("DoYouAlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email не может быть пустым.
        /// </summary>
        internal static string EmailCannotBeEmpty {
            get {
                return ResourceManager.GetString("EmailCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email не может содержать странных символов.
        /// </summary>
        internal static string EmailMustNotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("EmailMustNotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыл телефон?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзья.
        /// </summary>
        internal static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный пароль или Email.
        /// </summary>
        internal static string InvalidPasswordOrEmailAddress {
            get {
                return ResourceManager.GetString("InvalidPasswordOrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не является Email.
        /// </summary>
        internal static string IsNotAnEmail {
            get {
                return ResourceManager.GetString("IsNotAnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подходит.
        /// </summary>
        internal static string IsValid {
            get {
                return ResourceManager.GetString("IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ходы.
        /// </summary>
        internal static string Moves {
            get {
                return ResourceManager.GetString("Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя не может быть пустым.
        /// </summary>
        internal static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя не может содержать странных символов.
        /// </summary>
        internal static string NameMustNotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("NameMustNotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая игра.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Противник.
        /// </summary>
        internal static string Opponent {
            get {
                return ResourceManager.GetString("Opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партии.
        /// </summary>
        internal static string Parties {
            get {
                return ResourceManager.GetString("Parties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не может быть пустым.
        /// </summary>
        internal static string PasswordCannotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не может содержатьпробелы.
        /// </summary>
        internal static string PasswordCannotContainSpaces {
            get {
                return ResourceManager.GetString("PasswordCannotContainSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать 8 символов.
        /// </summary>
        internal static string PasswordMustBeAtLeast8Characters {
            get {
                return ResourceManager.GetString("PasswordMustBeAtLeast8Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать строчные буквы.
        /// </summary>
        internal static string PasswordMustContainLowercase {
            get {
                return ResourceManager.GetString("PasswordMustContainLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать цыфры.
        /// </summary>
        internal static string PasswordMustContainNumber {
            get {
                return ResourceManager.GetString("PasswordMustContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать специальные символы.
        /// </summary>
        internal static string PasswordMustContainSpecialChar {
            get {
                return ResourceManager.GetString("PasswordMustContainSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать Заглыные буквы.
        /// </summary>
        internal static string PasswordMustContainUppercase {
            get {
                return ResourceManager.GetString("PasswordMustContainUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не может содержать странных символов.
        /// </summary>
        internal static string PasswordMustNotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("PasswordMustNotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играть.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играть ~ 10 мин..
        /// </summary>
        internal static string Play10 {
            get {
                return ResourceManager.GetString("Play10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играть ~ 5 мин..
        /// </summary>
        internal static string Play5 {
            get {
                return ResourceManager.GetString("Play5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок черных.
        /// </summary>
        internal static string PlayerBlack {
            get {
                return ResourceManager.GetString("PlayerBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок белых.
        /// </summary>
        internal static string PlayerWhite {
            get {
                return ResourceManager.GetString("PlayerWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играть c друзьями.
        /// </summary>
        internal static string PlayWithFriends {
            get {
                return ResourceManager.GetString("PlayWithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рапид.
        /// </summary>
        internal static string Rapid {
            get {
                return ResourceManager.GetString("Rapid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистарация.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свернуть.
        /// </summary>
        internal static string RollUp {
            get {
                return ResourceManager.GetString("RollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый? Регистрация - начни играть!.
        /// </summary>
        internal static string SingUpButton {
            get {
                return ResourceManager.GetString("SingUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string SingUpButtonAndroid {
            get {
                return ResourceManager.GetString("SingUpButtonAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер доски.
        /// </summary>
        internal static string SizeBoard {
            get {
                return ResourceManager.GetString("SizeBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cтатистика.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Технологии.
        /// </summary>
        internal static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по имени или по имени пользователя.
        /// </summary>
        internal static string TextSearchByName {
            get {
                return ResourceManager.GetString("TextSearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроль времени.
        /// </summary>
        internal static string TimeControl {
            get {
                return ResourceManager.GetString("TimeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин, Телефон или Email.
        /// </summary>
        internal static string WatermarkLogin {
            get {
                return ResourceManager.GetString("WatermarkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string WatermarkPassword {
            get {
                return ResourceManager.GetString("WatermarkPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что это?.
        /// </summary>
        internal static string WhatThis {
            get {
                return ResourceManager.GetString("WhatThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почему Go?.
        /// </summary>
        internal static string WhyGo {
            get {
                return ResourceManager.GetString("WhyGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Победы.
        /// </summary>
        internal static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
    }
}
