//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShessBord.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShessBord.Resources.Strings.en-US", typeof(Strings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! My name is Artem Gamov, and this is my project — a Go application on Avalonia UI..
        /// </summary>
        internal static string Application1 {
            get {
                return ResourceManager.GetString("Application1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The classic board game Go (also known as Weizi) with a simple and user-friendly interface..
        /// </summary>
        internal static string Application2 {
            get {
                return ResourceManager.GetString("Application2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is written in C# using the Avalonia UI framework for cross-platform work (Windows, Linux, Android)..
        /// </summary>
        internal static string Application3 {
            get {
                return ResourceManager.GetString("Application3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suitable for both beginners and experienced players..
        /// </summary>
        internal static string Application4 {
            get {
                return ResourceManager.GetString("Application4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go is one of the oldest strategy games, combining simple rules with deep tactics. My goal is to make it available in digital format while preserving the elegance and atmosphere..
        /// </summary>
        internal static string Application5 {
            get {
                return ResourceManager.GetString("Application5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avalonia UI is for beautiful and responsive interfaces..
        /// </summary>
        internal static string Application6 {
            get {
                return ResourceManager.GetString("Application6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReactiveUI is for clean and flexible code..
        /// </summary>
        internal static string Application7 {
            get {
                return ResourceManager.GetString("Application7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET is the foundation for reliability and performance..
        /// </summary>
        internal static string Application8 {
            get {
                return ResourceManager.GetString("Application8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to suggest an idea or report a bug? Write:.
        /// </summary>
        internal static string Application9 {
            get {
                return ResourceManager.GetString("Application9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive of parties.
        /// </summary>
        internal static string ArchiveOfParties {
            get {
                return ResourceManager.GetString("ArchiveOfParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitz.
        /// </summary>
        internal static string Blitz {
            get {
                return ResourceManager.GetString("Blitz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board size.
        /// </summary>
        internal static string BoardSize {
            get {
                return ResourceManager.GetString("BoardSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet.
        /// </summary>
        internal static string Bullet {
            get {
                return ResourceManager.GetString("Bullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you already have an account?.
        /// </summary>
        internal static string DoYouAlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("DoYouAlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty.
        /// </summary>
        internal static string EmailCannotBeEmpty {
            get {
                return ResourceManager.GetString("EmailCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not contain special characters.
        /// </summary>
        internal static string EmailMustNotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("EmailMustNotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        internal static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password or Email address.
        /// </summary>
        internal static string InvalidPasswordOrEmailAddress {
            get {
                return ResourceManager.GetString("InvalidPasswordOrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not an Email.
        /// </summary>
        internal static string IsNotAnEmail {
            get {
                return ResourceManager.GetString("IsNotAnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string IsValid {
            get {
                return ResourceManager.GetString("IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves.
        /// </summary>
        internal static string Moves {
            get {
                return ResourceManager.GetString("Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        internal static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not contain special characters.
        /// </summary>
        internal static string NameMustNotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("NameMustNotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        internal static string Opponent {
            get {
                return ResourceManager.GetString("Opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parties.
        /// </summary>
        internal static string Parties {
            get {
                return ResourceManager.GetString("Parties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password сannot be empty.
        /// </summary>
        internal static string PasswordCannotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password сannot сontain spaces.
        /// </summary>
        internal static string PasswordCannotContainSpaces {
            get {
                return ResourceManager.GetString("PasswordCannotContainSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters.
        /// </summary>
        internal static string PasswordMustBeAtLeast8Characters {
            get {
                return ResourceManager.GetString("PasswordMustBeAtLeast8Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain lowercase.
        /// </summary>
        internal static string PasswordMustContainLowercase {
            get {
                return ResourceManager.GetString("PasswordMustContainLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain number.
        /// </summary>
        internal static string PasswordMustContainNumber {
            get {
                return ResourceManager.GetString("PasswordMustContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain special char.
        /// </summary>
        internal static string PasswordMustContainSpecialChar {
            get {
                return ResourceManager.GetString("PasswordMustContainSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain upper case.
        /// </summary>
        internal static string PasswordMustContainUppercase {
            get {
                return ResourceManager.GetString("PasswordMustContainUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not contain special characters.
        /// </summary>
        internal static string PasswordMustNotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("PasswordMustNotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing ~ 10 min..
        /// </summary>
        internal static string Play10 {
            get {
                return ResourceManager.GetString("Play10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing ~ 5 min..
        /// </summary>
        internal static string Play5 {
            get {
                return ResourceManager.GetString("Play5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player black.
        /// </summary>
        internal static string PlayerBlack {
            get {
                return ResourceManager.GetString("PlayerBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player white.
        /// </summary>
        internal static string PlayerWhite {
            get {
                return ResourceManager.GetString("PlayerWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play with friends.
        /// </summary>
        internal static string PlayWithFriends {
            get {
                return ResourceManager.GetString("PlayWithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid.
        /// </summary>
        internal static string Rapid {
            get {
                return ResourceManager.GetString("Rapid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll up.
        /// </summary>
        internal static string RollUp {
            get {
                return ResourceManager.GetString("RollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New? Sing up - and start playing chess!.
        /// </summary>
        internal static string SingUpButton {
            get {
                return ResourceManager.GetString("SingUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string SingUpButtonAndroid {
            get {
                return ResourceManager.GetString("SingUpButtonAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size board.
        /// </summary>
        internal static string SizeBoard {
            get {
                return ResourceManager.GetString("SizeBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologies.
        /// </summary>
        internal static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name or by username.
        /// </summary>
        internal static string TextSearchByName {
            get {
                return ResourceManager.GetString("TextSearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time control.
        /// </summary>
        internal static string TimeControl {
            get {
                return ResourceManager.GetString("TimeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username, Phone , or Email.
        /// </summary>
        internal static string WatermarkLogin {
            get {
                return ResourceManager.GetString("WatermarkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string WatermarkPassword {
            get {
                return ResourceManager.GetString("WatermarkPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What this?.
        /// </summary>
        internal static string WhatThis {
            get {
                return ResourceManager.GetString("WhatThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Go?.
        /// </summary>
        internal static string WhyGo {
            get {
                return ResourceManager.GetString("WhyGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        internal static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
    }
}
